### ISSUE TITLE
Issues in inpainting

### ISSUE THREAD

**Issue by Gourab0002** [DCY1117/MangaQuick#3]
Bro i tried translating but i am getting thus issue. Please help me.

 [Errno 2] No such file or directory: 'prediction/inpainting/01/01_mask.png'
Traceback:
File "C:\Users\goura\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\goura\Downloads\MangaQuick\MangaQuick.py", line 469, in <module>
    text_injection(
File "C:\Users\goura\Downloads\MangaQuick\components\text_injection.py", line 24, in text_injection
    image = Image.open(f'prediction/inpainting/{name}/{mask_name}')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\goura\anaconda3\Lib\site-packages\PIL\Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Again I tried and got this error.

[WinError 2] The system cannot find the file specified: 'C:\\Users\\goura\\Downloads\\MangaQuick/prediction/translated'
Traceback:
File "C:\Users\goura\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "C:\Users\goura\Downloads\MangaQuick\MangaQuick.py", line 500, in <module>
    shutil.make_archive('translated', 'zip', f'{current_directory}/prediction/translated')
File "C:\Users\goura\anaconda3\Lib\shutil.py", line 1120, in make_archive
    stmd = os.stat(root_dir).st_mode
           ^^^^^^^^^^^^^^^^^

PLEASE HELP.

**Comment by Gourab0002** [comment]
More info-

Traceback (most recent call last):
  File "C:\Users\goura\Downloads\MangaQuick/components/image_inpainting/bin/predict.py", line 14, in <module>
    from saicinpainting.evaluation.utils import move_to_device
  File "C:\Users\goura\Downloads\MangaQuick\components\image_inpainting\bin\saicinpainting\evaluation\__init__.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
2024-04-14 00:49:56.140 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\goura\anaconda3\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\goura\Downloads\MangaQuick\MangaQuick.py", line 469, in <module>
    text_injection(
  File "C:\Users\goura\Downloads\MangaQuick\components\text_injection.py", line 24, in text_injection
    image = Image.open(f'prediction/inpainting/{name}/{mask_name}')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\goura\anaconda3\Lib\site-packages\PIL\Image.py", line 3247, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'prediction/inpainting/03/03_mask.png'

**Comment by Gourab0002** [comment]
ok so i have never used python so i am getting error about not having many modules. what can I do

**Comment by Gourab0002** [comment]
ok so, I fixed it. Gave me a lot of trouble. Took total of 4 hours. But hey got it. Thanks for the project btw.
