### ISSUE TITLE
Error running in google colab

### ISSUE THREAD

**Issue by rsaurav12** [DCY1117/MangaQuick#5]
I try to run in google colab but i'm constantly facing this issue :
2024-12-05 18:38:08.898782: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-05 18:38:08.940785: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-05 18:38:08.953008: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-05 18:38:08.982709: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-12-05 18:38:10.573639: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-12-05 18:38:12.181 Uncaught app exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/content/MangaQuick/MangaQuick.py", line 188, in <module>
    text_segmentation_model = load_segmentation_model(segmentation_device, model_name)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/caching/cache_utils.py", line 212, in wrapper
    return cached_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/caching/cache_utils.py", line 241, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/caching/cache_utils.py", line 268, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/caching/cache_utils.py", line 324, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/content/MangaQuick/MangaQuick.py", line 183, in load_segmentation_model
    model = load_learner('.', f'components/text_detection/models/{model_name}')
  File "/usr/local/lib/python3.10/dist-packages/fastai/learner.py", line 448, in load_learner
    try: res = torch.load(fname, map_location=map_loc, pickle_module=pickle_module)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1319, in load
    with _open_file_like(f, "rb") as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 659, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 640, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: '.'
2024-12-05 18:38:12.979 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

And all models are in correct path
![Screenshot_2024-12-06-00-13-44-093_com brave browser](https://github.com/user-attachments/assets/327d8997-97ce-47ee-a903-e6c127373b98)

**Comment by DCY1117** [comment]
I believe the issue may have been caused by certain library versions changed in a recent pull request. The problem should now be resolved. Please let me know if it’s working on your end. Additionally, I’ve updated the README with instructions for using MangaQuick on Colab and included a Colab notebook to simplify running Streamlit. You might find this approach more convenient.

**Comment by DCY1117** [comment]
Also, check the related repositories mentioned in the README—they are really good.

**Comment by rsaurav12** [comment]
> I believe the issue may have been caused by certain library versions changed in a recent pull request. The problem should now be resolved. Please let me know if it’s working on your end. Additionally, I’ve updated the README with instructions for using MangaQuick on Colab and included a Colab notebook to simplify running Streamlit. You might find this approach more convenient.

Yes it's working now and you have done an awesome work!! Thank you and i kindly request you to implement other Translators Reference (from https://github.com/zyddnys/manga-image-translator) other than deepl 🙏

**Comment by DCY1117** [comment]
Thank you!! As for adding other translator references from [zyddnys/manga-image-translator](https://github.com/zyddnys/manga-image-translator), I’m no longer actively maintaining or improving this repository. This [zyddnys/manga-image-translator](https://github.com/zyddnys/manga-image-translator) tool and similar projects may be more up-to-date and feature-rich, making them potentially better options moving forward.

That said, I’d love to hear your thoughts. What advantages do you see in using my app compared to the other solutions out there? Understanding this might help me (or anyone interested) see if there’s value in revisiting or improving this project in the future.

But anyway, I’ll keep your suggestion in mind and maybe implement it in the near future if i have time.

**Comment by rsaurav12** [comment]
Advantages are too many maybe i will miss something. But key advantages are obviously cool web ui !!! , ability to add batch images at once , ability to select models and i would like to know about more models too, same way i would love to have options for selecting various translations models available in [zyddyns](https://github.com/zyddnys/manga-image-translator) repo like "sugoi",  and i liked the ability to change text box size, able to change languages  and fonts, i would to have options to change denoise levels and size of images. It's seems i'm trying to be very demanding but i liked your project very much😄 and i see potential in it. Whenever if you have time please implement this features, i'm looking forward to it.

(web ui is pretty outdated in [zyddyns](https://github.com/zyddnys/manga-image-translator) repo, there is no batch translation  through web ui and nothing much to customise in it although i really loved that project too)
